apiVersion: v1
kind: Service
metadata:
  name: comingsoon-page
  namespace: laravel-app
spec:
  selector:
    app: comingsoon-page
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: NodePort
  ports:
  - protocol: TCP
    port: 3306 
    targetPort: 3306 