apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    run: webserver
  namespace: laravel-app
spec:
  selector:
    app: db
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: NodePort
  ports:
  - protocol: TCP
    port: 3306 
    targetPort: 3306 