pipeline {
    agent any

    stages {

        stage('Delete Cluster') {
            steps {
              // Ignore failure if the cluster does not exist
              catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
              // You will need to install CloudBees AWS Credentials Plugin in Jenkins and add AWS Credentials first 
                withCredentials([[
                  $class: 'AmazonWebServicesCredentialsBinding',
                  credentialsId: "aws-credentials",
                  accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                  secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                  ]]) {
                  sh "eksctl delete cluster --name laravelapp-cluster --region eu-central-1"
                  sleep(time: 180, unit: "SECONDS")
                }
                
                sh "exit 1"
              }  
            }
        }

        // stage('Create Cluster') {
        //     steps {
        //       // You will need to install CloudBees AWS Credentials Plugin in Jenkins and add AWS Credentials first 
        //         withCredentials([[
        //           $class: 'AmazonWebServicesCredentialsBinding',
        //           credentialsId: "aws-credentials",
        //           accessKeyVariable: 'AWS_ACCESS_KEY_ID',
        //           secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
        //           ]]) {
        //           sh """
        //           eksctl create cluster --name laravelapp-cluster --region eu-central-1 --nodes-min=3
        //           aws eks update-kubeconfig --name laravelapp-cluster
        //           """
        //         }
        //     }
        // }

        // stage('Create Namespace') {
        //     steps {
        //       // You will need to install CloudBees AWS Credentials Plugin in Jenkins and add AWS Credentials first 
        //         withCredentials([[
        //           $class: 'AmazonWebServicesCredentialsBinding',
        //           credentialsId: "aws-credentials",
        //           accessKeyVariable: 'AWS_ACCESS_KEY_ID',
        //           secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
        //           ]]) {
        //           sh "kubectl create namespace laravel-app"
        //         }
        //     }
        // }
    }
}